### ISSUE TITLE
Сервер создает крупные лаги когда на нем никого нет!!!

### ISSUE THREAD

**Issue by FFLomka** [glebqip/metrostroi_beta#15]
![58123](https://cloud.githubusercontent.com/assets/13985164/9665704/9122de78-527a-11e5-8daa-a8cb9948f96d.png)

**Comment by glebqip** [comment]
Когда нет поездов сигналка всё равно проводит свои вычисления(если хоть один игрок заходил). 6% это не смертельная нагрузка. Если так надо то можно сделать остановку вычислений при отсутствии игроков и поездов. В будущем буду смотреть что можно оптимизировать.
