### ISSUE TITLE
[ERROR] addons/metrostroi/lua/entities/gmod_subway_81-717_new/init.lua:376

### ISSUE THREAD

**Issue by Foxy33** [glebqip/metrostroi_beta#23]
[ERROR] addons/metrostroi/lua/entities/gmod_subway_81-717_new/init.lua:376: attempt to index a nil value
  1. unknown - addons/metrostroi/lua/entities/gmod_subway_81-717_new/init.lua:376

**Comment by glebqip** [comment]
b0aef9a4eac376f56cb61b75a8fbe66eafb9a7cf
