### ISSUE TITLE
[ERROR] addons/metrostroi/lua/entities/gmod_subway_81-717_new/init.lua:377

### ISSUE THREAD

**Issue by Foxy33** [glebqip/metrostroi_beta#24]
[ERROR] addons/metrostroi/lua/entities/gmod_subway_81-717_new/init.lua:377: attempt to index a nil value
  1. unknown - addons/metrostroi/lua/entities/gmod_subway_81-717_new/init.lua:377

**Comment by glebqip** [comment]
a2b89df900fb9ab44af7493fe062b2ea70ae0e09

**Comment by Foxy33** [comment]
Ошибка осталась

**Comment by Foxy33** [comment]
Бл*
Теперь...
[ERROR] addons/metrostroi/lua/entities/gmod_subway_81-717_new/init.lua:379: attempt to index a nil value
  1. unknown - addons/metrostroi/lua/entities/gmod_subway_81-717_new/init.lua:379
