### ISSUE TITLE
Маршруты

### ISSUE THREAD

**Issue by Crusher52rus** [glebqip/metrostroi_beta#27]
Не собирается маршрут с первого пути в оборот (ст. Минская). Светофор MN337 ("Нет поезда перед светофором"). Перед светофором MN339 маршруты работают (и 3 и 4 путь).

**Comment by glebqip** [comment]
Если поезда нет, то стрелки обратно переводятся

**Comment by Crusher52rus** [comment]
Ты видать меня не совсем понял...
