### ISSUE TITLE
Информатор-франкенштейн

### ISSUE THREAD

**Issue by CodersGit** [glebqip/metrostroi_beta#28]
![2015-09-11_00001](https://cloud.githubusercontent.com/assets/3987278/9815858/15bd7526-58bb-11e5-8342-bad38d14d9c6.jpg)
Появляется через раз. Похоже, поверх питерской панели АЛС/АРС спавнится еще и московская с круглыми лампами (Точнее, кнопки от нее).
Параметры в трейн спавнере:
![2015-09-11_00002](https://cloud.githubusercontent.com/assets/3987278/9815975/d419ac92-58bb-11e5-8e32-0c11467afecf.jpg)

**Comment by glebqip** [comment]
Хмм, этот баг фиксился очень долго. Опять появляется

**Comment by CodersGit** [comment]
Сколько коммитов назад фиксился?

**Comment by glebqip** [comment]
С самого первого. Хотя стоп - тут похоже на клиентскую\серверную ошибку, т.к. горят ЛКВД и АВУ, но не горит скоростемер. Скоростемер должен гореть вместе с АВУ (точный предпризнак включения батареи). Плюс кран в неестественном положении. Сервер какой?

**Comment by CodersGit** [comment]
Сервер Романа. В ЗК горел скоростеметр, но не там, где должен был быть на питерской панели АРС. Также в ЗК не там спавнились автоматы и КВ в Т2 при нулевом реверсе (при том КВ можно было перемещать кнопками на клаве). Видно было не только мне, но баг больше никто не воспроизвел, хотя у меня он повторялся для каждого состава, заспавненного с опциями как на скриншоте. Кружка-прицела не было.

**Comment by glebqip** [comment]
Это уже проблема сетевого гмода, а если точнее получения данных с сервера
