### ISSUE TITLE
Светофоры и их линзы

### ISSUE THREAD

**Issue by Crusher52rus** [glebqip/metrostroi_beta#30]
Нечего говорить. Линзы светофоров смещены влево.
![2015-09-14_00001](https://cloud.githubusercontent.com/assets/14218680/9843242/0692fe24-5ac1-11e5-9d06-7b62bb7310bf.jpg)
![2015-09-14_00002](https://cloud.githubusercontent.com/assets/14218680/9843241/06917fc2-5ac1-11e5-811e-12540ffa4d1a.jpg)
![2015-09-14_00003](https://cloud.githubusercontent.com/assets/14218680/9843244/0693dc04-5ac1-11e5-8323-00a49626779e.jpg)
![2015-09-14_00004](https://cloud.githubusercontent.com/assets/14218680/9843243/069352c0-5ac1-11e5-8899-1901cf989046.jpg)
![2015-09-14_00005](https://cloud.githubusercontent.com/assets/14218680/9843245/06951434-5ac1-11e5-96b4-b91769fd0626.jpg)

**Comment by glebqip** [comment]
a0d3f65e92553da630e5a216ccbe899cb53b9f65
