### ISSUE TITLE
Проблема с АРС на перегоне Минская-Синеозерная

### ISSUE THREAD

**Issue by msdas** [glebqip/metrostroi_beta#32]
На перегоне Минская-Синеозерная (конкретнее Минская-Лесная) АРС показывает 80-ти, но на деле больше 20-ти ехать нельзя, АРС пищит, поезд начинает останавливаться...

**Comment by CodersGit** [comment]
ПБ отпускать надо. С педалью бдительности разгнаться более 20 км/ч нельзя.

**Comment by glebqip** [comment]
Отожми ПБ
