### ISSUE TITLE
Реверсивка

### ISSUE THREAD

**Issue by Foxy33** [glebqip/metrostroi_beta#34]
При попытке воспользоваться реверсивкой выдаёт вот это

[ERROR] addons/metrostroi/lua/entities/gmod_subway_base/init.lua:1877: attempt to call method 'CPPICanPhysgun' (a nil value)
  1. func - addons/metrostroi/lua/entities/gmod_subway_base/init.lua:1877
   2. unknown - lua/includes/extensions/net.lua:32

**Comment by glebqip** [comment]
2 вопроса - Prop protection есть? И какой?
