### ISSUE TITLE
Фары на красной стреле

### ISSUE THREAD

**Issue by KyppuTTo** [glebqip/metrostroi_beta#35]
Не видно света фар на красной стреле. Светит как обычно, но на маске не видно (На скриншоте фары и ВУС включены)
![2015-09-15_00002](https://cloud.githubusercontent.com/assets/2605870/9862249/3e20a13c-5b40-11e5-865e-7a0ca46abd16.jpg)

**Comment by CodersGit** [comment]
Ничего то, что красной стрелы с маской 2-2 не существует?

**Comment by nik133133** [comment]
Ты прав, но это не значит, что фары не должны работать.
