### ISSUE TITLE
Срыв УАВА на самого себя.

### ISSUE THREAD

**Issue by OnlyNoob** [glebqip/metrostroi_beta#36]
При малой скорости если проехать светофор может сорвать УАВА.

**Comment by glebqip** [comment]
Показание светофора какое было?

**Comment by OnlyNoob** [comment]
Я же рассказывал уже когда то, так вон так и остался.
Там едешь например в депо или просто неважно, светофор белый или зеленый соответственно, проезжаешь не сильно быстро и ну там где то на половине 1 вагона он меняется на красный и когда хвостовой проезжает в нем срывает.
