### ISSUE TITLE
Управление кнопками снаружи

### ISSUE THREAD

**Issue by Crusher52rus** [glebqip/metrostroi_beta#37]
На прицепных вагонах воздуханы и ГВ всё так-же переключаются на букву E
![2015-09-15_00001](https://cloud.githubusercontent.com/assets/14218680/9888971/bb84feaa-5c00-11e5-8e57-ae2cec7d6f65.jpg)
![2015-09-15_00002](https://cloud.githubusercontent.com/assets/14218680/9888972/bb8db91e-5c00-11e5-9f66-467b48b9b304.jpg)
Вот так это должно быть:
![2015-09-15_00004](https://cloud.githubusercontent.com/assets/14218680/9888976/c75f5bb2-5c00-11e5-816e-262865c1d0b7.jpg)
![2015-09-15_00003](https://cloud.githubusercontent.com/assets/14218680/9888975/c75d30d0-5c00-11e5-8787-bd7bafe1e799.jpg)

**Comment by glebqip** [comment]
Прицепные пока не обновлялись
