### ISSUE TITLE
"Ствояночный тормоз"

### ISSUE THREAD

**Issue by Crusher52rus** [glebqip/metrostroi_beta#40]
Без комментариев...
![2015-09-20_00001](https://cloud.githubusercontent.com/assets/14218680/9980933/26cfd984-5fb5-11e5-9076-fa0f48fbae76.jpg)

P.S. Ошибка с самого его появления :D

**Comment by glebqip** [comment]
b57c3272e24fe0d3eafe7d43e1e26a3b9d75a310
