### ISSUE TITLE
В нормальном состоянии БПСН "мигает"

### ISSUE THREAD

**Issue by CodersGit** [glebqip/metrostroi_beta#42]
Т.е. включается-выключается, при том очень быстро. Перестает так делать только в движении или при влюченном ВАХе (носенс!). Версия самая последняя.

**Comment by glebqip** [comment]
714 есть в составе?

**Comment by CodersGit** [comment]
Да.

**Comment by glebqip** [comment]
Жди обновы, это вроде как профикшено. Для уточнения - так же моргает лампа защиты преобразователя?

**Comment by CodersGit** [comment]
Да, со сдвигом на пол фазы.

**Comment by glebqip** [comment]
Уже профикшено. Жди обновы(сегодня-послезавтра)

**Comment by CodersGit** [comment]
Ну и?..

**Comment by glebqip** [comment]
Просьба проверить

**Comment by CodersGit** [comment]
Весьма забавно, но на других серверах кроме моего локального по результатам вчерашней моей проверки проблем не было. Проверю эту версию.

**Comment by CodersGit** [comment]
714 полностью перестал работать, не меняет текстуру, не включается ВБ и т.д.

**Comment by CodersGit** [comment]
[ERROR] addons/metrostroi/lua/entities/gmod_subway_81-714_new/init.lua:202: attempt to perform arithmetic on field 'SpeedSign' (a nil value)
  1. unknown - addons/metrostroi/lua/entities/gmod_subway_81-714_new/init.lua:202
