### ISSUE TITLE
При создании состава выводится ошибка

### ISSUE THREAD

**Issue by cyber-dream** [glebqip/metrostroi_beta#43]
[ERROR] addons/metrostroi/lua/entities/gmod_subway_81-717_new/init.lua:357: attempt to compare number with nil
  1. unknown - addons/metrostroi/lua/entities/gmod_subway_81-717_new/init.lua:357

**Comment by cyberdart** [comment]
Решено. Турбострой имеет зависимости от 10-ой студии.
