### ISSUE TITLE
Смещение элементов на питерской панели АЛС/АРС и Иглы

### ISSUE THREAD

**Issue by CodersGit** [glebqip/metrostroi_beta#44]
Видно, что чуть смещено все от центра. Также лучше чуть выдвинуть ближе к игроку, ибо полигоны находятся на одном уровне и при движении попеременно загораживают друг друга
![2015-10-04_00004](https://cloud.githubusercontent.com/assets/3987278/10266480/af109ba8-6a87-11e5-8b07-0c270942f505.jpg)
![2015-10-04_00001](https://cloud.githubusercontent.com/assets/3987278/10266481/af349e36-6a87-11e5-9ce4-5187e9212c78.jpg)
![2015-10-04_00002](https://cloud.githubusercontent.com/assets/3987278/10266482/af5c8310-6a87-11e5-977f-c3d848a3543c.jpg)

**Comment by glebqip** [comment]
Питерская АРС профикшена
