### ISSUE TITLE
Одиночка

### ISSUE THREAD

**Issue by ivbatarin** [glebqip/metrostroi_beta#46]
Закинул в папку с игрой содержимое архива. При загрузке выскакивает окно (фотография 1), затем при создании состава появляется просто кузов. Установлена карта b50 с Workshop
![2015-10-04_00001](https://cloud.githubusercontent.com/assets/14967314/10269651/1575f97a-6ae6-11e5-8fdc-3a9d2173e9f7.jpg)
![2015-10-04_00002](https://cloud.githubusercontent.com/assets/14967314/10269652/1576bcf2-6ae6-11e5-9455-38c6bf2c4f9c.jpg)

**Comment by glebqip** [comment]
Первое всегда будет выскакивать в одиночке - она не предназначена для игры в метрострой
Второе - повысь качество моделей
