### ISSUE TITLE
Не меняется текстура ежа при перекраске

### ISSUE THREAD

**Issue by CodersGit** [glebqip/metrostroi_beta#47]
При перекраске ежа (или ема) не меняется текстура его корпуса. При том текстура дверей меняется.

Занаю, е-подобными ты тейчас не занимаешься, просто кинул таск.

P.S. По поводу нашего с тобой недавнего открытие про оранжевый не PNM информатор. Думаю, самый простой способ - приложить подорожник в виде переименовывания папки subway_announcer в, напимер, subway_announcer_default.

**Comment by glebqip** [comment]
P.S. - как идея

**Comment by CodersGit** [comment]
Кинул фикс в пулл реквесте https://github.com/glebqip/metrostroi_beta/pull/48

**Comment by glebqip** [comment]
15dc2f298562c143830d6bc888c930a49b26840a
