### ISSUE TITLE
[MAIN CODE] PA-KSD-M does not allow changing the destination after finishing a route

### ISSUE THREAD

**Issue by Th4nato5** [glebqip/metrostroi_beta#52]
I tried to change the destination using the PA-KSD-M system after making the last stop at Airport on the Orange line and wanted to switch to the Red line and change the destination to Metro Builders staiton. However, it would not change at all. Any ideas?

P.S. Will there be a English translation for the PA-KSD-M system, like how the PA-KSD is translated to English? Or will there be a manual to provide a step-by-step instruction on how to use it (rather than translating the entire system)?

**Comment by glebqip** [comment]
For change you need Фиксация станции(first station and line set) and Зонный оборот(last station set). Or try Смена настроек(full settings change)

**Comment by Th4nato5** [comment]
Alright, thanks.

**Comment by Th4nato5** [comment]
Okay, I just tried a run in Garry's Mod and the Full Settings Change option does not work when I pressed it.

**Comment by glebqip** [comment]
HmmDoing. off->on PA-KSD-M via VPA

**Comment by Th4nato5** [comment]
I don't see VPA on the panel....

**Comment by glebqip** [comment]
ВПА, where must be ARS switch

**Comment by Th4nato5** [comment]
Whoops... Saw it now. Thanks.
