### ISSUE TITLE
[MAIN CODE] No DURA system on the PA-KSD or PA-KSD-M systems or buttons for the DURA system

### ISSUE THREAD

**Issue by Th4nato5** [glebqip/metrostroi_beta#53]
I tried to access the DURA system via PA-KSD and PA-KSD-M and found that it's not possible to change the track unless I press the hotkeys for switching the track. For example, I spawned a train in -b50 at the tail tracks near Station #322 and I thought there was a way to use the Computer System (or press the buttons) in order to switch the track to head towards Station #321, rather than pressing the hotkeys for the DURA switch. Will there be something added to the 81-717 LVZ trains in order to add the DURA switches to these systems (or somehow access the DURA system using the on-board computer system)?

**Comment by glebqip** [comment]
LVZ don't have DURA. Maybe, i built it in the autodrive systems (you still can use metrostroi_track_alt and metrostroi_track_main with channel number as 1st argument of console command)

**Comment by Th4nato5** [comment]
I believe this issue is fixed with the release of the Motorola system on LVZ trains. However, a new problem popped up where the destination boards for the front end of the train switches with the back end of the train (For example, a train starting from 401 to 408 would have its signs on the front end switched to Airport, instead of Garry's Mod Workers.). In addition, the destination boards can't be fixed when editing the settings or restarting the entire system and an error pops up in the console as well.

**Comment by glebqip** [comment]
For "orange" signs - i can do this, but not now
