### ISSUE TITLE
[ORANGE, BUG] PA-KSD and PA-KSD-M station listing for Line 1 (401-408)

### ISSUE THREAD

**Issue by Th4nato5** [glebqip/metrostroi_beta#55]
Since the recent update for the Orange map, I tried the PA-KSD and PA-KSD-M for lines 1, 2, and 3 and I have discovered the following bugs:

PA-KSD and PA-KSD-M
-The stations are now different and the listing used on the two systems are based on the last version of the map (Ver. F), i.e. It's supposed to be Lithium -> Park -> GCFScape. On both systems, it shows Lithium -> GCFScape.
-Console shows missing sounds, i.e. Create Stream Failed error 41
Failed to load sound "subway_stations_test1\_3.mp3", file probably missing from disk/repository

PA-KSD
-The signals and signal labels for line 3 (and most likely line 2 as well) are producing console errors when using PA-KSD on that line. For example, it would show a distance of 9999.0 m when running from Wallace Breen to Brate'evo.

PA-KSD-M
-At the last station of the subway line, PA-KSD-M continues to broadcast into the train about the current station, but stopped immediately when it realizes that there's no next station. For example, after dropping off the passengers at Airport, the system (I believe this is UPO) continues to broadcast into the train about the current station and tries to broadcast the next station on the line (but in reality, there's no next station).

**Comment by glebqip** [comment]
Hmm, all systems are compatible with metro_h.
"Failed to load sound" - what map? If metro_h - redownload addon. Some can broke it.
"The signals and signal labels are producing console errors" - what errors?
"At the last station of the subway line, PA-KSD-M continues to broadcast into the train about the current station" - yeah, i know. It wont turn a line(as you can see - you still on 1st line) and create server script errors(can't find next station) Need split tracks.
