### ISSUE TITLE
Отсутствуют звуки разгона и торможения ТЭДов

### ISSUE THREAD

**Issue by fx83** [glebqip/metrostroi_beta#57]
При движении поезда отсутствуют звуки разгона и торможения ТЭДов. Их действительно нет в папке со звуками, вместо этого лежат только файлы с расширением *.sfk:
![teds](https://cloud.githubusercontent.com/assets/16718801/12352466/52682892-bb97-11e5-9c89-34e7ecc034a7.png)

**Comment by glebqip** [comment]
Омг, огромное спасибо что обнаружил. В воркшопе все.нормально, а тут...

**Comment by glebqip** [comment]
8fd75326f4899588a227a33d91f6d6aad43a5f44
