### ISSUE TITLE
[BUG] 81-714/717 LVZ and MVM bugs

### ISSUE THREAD

**Issue by Th4nato5** [glebqip/metrostroi_beta#60]
1. When opening the door for the first time on the MVM variant of the train (not sure about LVZ), the doors would not open on the correct side. For example, when I first opened the door on the right side of the train at Airport Station, the 1st car would open its right side doors, while the 2nd and 3rd cars would open the left side doors (right-hand side of the other end).
2. The announcer function of the MVM variant trains displays correct menu functions. However, after finalizing the changes, the announcer does not work at all and displays a blank text screen.
3. On the LVZ variant trains, the PA-KSD-M and PA-KSD system does not allow the user to enter the train number ("Маршрут"), where pressing any number (1-9) would not be input into the field. This prevents the system from being used at all. However, the front of the train still displays the destination board, but shows the Train number as 00. 

Note: This error shows up in the console:

[ERROR] addons/metrostroi/lua/metrostroi/systems/sys_upo.lua:160: attempt to call method 'GetLastWagon' (a nil value)
1. ReloadSigns - addons/metrostroi/lua/metrostroi/systems/sys_upo.lua:160
2. SetStations - addons/metrostroi/lua/metrostroi/systems/sys_upo.lua:173
3. UpdateUPO - addons/metrostroi/lua/metrostroi/systems/sys_pa-ksd.lua:494
4. Trigger - addons/metrostroi/lua/metrostroi/systems/sys_pa-ksd.lua:573
5. Think - addons/metrostroi/lua/metrostroi/systems/sys_pa-ksd.lua:1027
6. Think - addons/metrostroi/lua/entities/gmod_subway_base/init.lua:1617
7. unknown - addons/metrostroi/lua/entities/gmod_subway_81-717_lvz/init.lua:485

4. The Orange Metro train line maps for the LVZ and MVM variant trains are now displayed properly, but does not show the correct lines. LVZ trains still show the line map of the previous version of the Orange Metro map, while the MVM trains are missing the Green line for the line map.

**Comment by glebqip** [comment]
1) It's very very old bug and i think, i can't fix it.
2) I started a announcer rewrote - wait next version
3) I will check and fix, thx

1) Hmm, can you show?

**Comment by Th4nato5** [comment]
For the doors, I think it was like that for the first time. But afterwards, it was fine on all of the other stations.

**Comment by Th4nato5** [comment]
LVZ trains:

http://images.akamai.steamusercontent.com/ugc/358401785615997178/F5EF24F97C8C33A58A19B62C75FEF345BA56C619/

**Comment by Th4nato5** [comment]
Additional Bugs:
1) Station list on a PA-KSD-M train is still incorrect for Line 1 on the Orange Metro map
2) Announcement system does not announce the station stop voice recordings for LVZ variant trains does not work at all (Most like due to the ASNP not fully ready yet)
3) PA-KSD-M and PA-KSD show incorrect destination boards at the beginning of system setup (shows the station of origin on the board, instead of the destination).
4) Pneumatic System Failure occurs when changing the throttles in this order: T2 -> 0 -> X1 -> T2 -> X1. (This is used when adjusting train stopping position at Garry's Mod Worker station due to the Gap fillers on the station platform)

Other Notes:
1) The announcement system for MVM trains works very well, along with the destination boards.

**Comment by glebqip** [comment]
1) It's map error, not my. I can fix it temporarily, but for example i can't fix Brateevo, Pionerskaya and small script station size
