### ISSUE TITLE
[BUG]81-714 mvm lamp power error

### ISSUE THREAD

**Issue by kfmboy** [glebqip/metrostroi_beta#61]
Third rail have power, batteries on, Main switch on, and when I switch on wagon light, at 84-717 lights on, but 81-714 not. Only the emergency lights on in the 81-714.

**Comment by glebqip** [comment]
Thx, i will fix it

**Comment by kfmboy** [comment]
At the latest version, this bug did not come, but I  think, I have found new bug with lamp function:
when one car of the train have high voltage from third rail, all cars's lamp lighting with full power. In the older 81 series in Budapest, only that car's lamp lighting, witch have high voltage, the anoter one have only emergency light.

**Comment by glebqip** [comment]
kfmboy - BPSN have 2-3sec emergency lighting delay

**Comment by kfmboy** [comment]
OK, but this lighting problem permanent:
- First car is on third rail, second and third in depo, without high voltage.
- The voltage meter is only in the first car detect the high voltage.
- I'm turning on the main switch and battery at all car (emergency light turning on at all cars).
- Switcing on the inverter, then  switch on wagon light.
= At all cars, the lights turning on permanent.

I think, just the first car must be permanent full light, second and third car must be only emergency light. (the earlier version worked this way)
