### ISSUE TITLE
При открытии клапана разобщения звук как будто выходит воздух медленно

### ISSUE THREAD

**Issue by Sashavodn** [glebqip/metrostroi_beta#65]
После последнего обновления при открытии клапана разобщения и ЭПК,странный звук как будто медленно выходит воздух (стрелки давления показывают что воздух не уходит).
При этом поезд полностью функционирует.У других людей так же наблюдалась эта проблема.

**Comment by glebqip** [comment]
Это естественная утечка из ТМ(или НМ, ещё инфы нет). Этот звук есть в реальности
