### ISSUE TITLE
Питерская ARS Панель / St.Petersburg ARS Panel

### ISSUE THREAD

**Issue by Hellss** [glebqip/metrostroi_beta#68]
![2016-02-21_00006](https://cloud.githubusercontent.com/assets/16958912/13204881/f72487e2-d8eb-11e5-9455-23fdbd0f4412.jpg)
![2016-02-21_00003](https://cloud.githubusercontent.com/assets/16958912/13204882/fb997cd8-d8eb-11e5-806a-4abf7a2552fa.jpg)

**Comment by glebqip** [comment]
Спасибо
