### ISSUE TITLE
Error in console server

### ISSUE THREAD

**Issue by alexeib1** [glebqip/metrostroi_beta#71]
Переодически консоль выбивает ошибки

![default](https://cloud.githubusercontent.com/assets/17434146/13257784/63daa8b4-da7a-11e5-9917-cc17755ea345.png)
![1](https://cloud.githubusercontent.com/assets/17434146/13260284/01f1beac-da85-11e5-9077-4794682c0f25.png)

**Comment by glebqip** [comment]
Первое - какая карта? Второе уже профикшено

**Comment by alexeib1** [comment]
gm_mus_orange_metro_h

**Comment by alexeib1** [comment]
вот еще ошибка, уже сегодня 
![default](https://cloud.githubusercontent.com/assets/17434146/13348172/194bd4f2-dc9c-11e5-9ee3-9603dc4613ba.png)

**Comment by alexeib1** [comment]
еще одна ошибка карта gm_mus_orange_metro_h
![2](https://cloud.githubusercontent.com/assets/17434146/13356520/d6975f30-dccf-11e5-8e4d-5ac303be1d7a.png)

**Comment by alexeib1** [comment]
еще одна.
![3](https://cloud.githubusercontent.com/assets/17434146/13370673/1b8b2dce-dd39-11e5-9085-f8d0ec48e303.png)

**Comment by alexeib1** [comment]
ошибки на обновлении от 28.02.2016 карта **gm_mus_orange_metro_h**
![updatemetro28](https://cloud.githubusercontent.com/assets/17434146/13379124/ba850832-de47-11e5-8bb0-1917a03f751c.png)
![updatemetro28error2](https://cloud.githubusercontent.com/assets/17434146/13379125/ba85baf2-de47-11e5-81fa-8d8a3a9b9055.png)

**Comment by glebqip** [comment]
Train feature editor не работает

**Comment by alexeib1** [comment]
в будущем будет пофикшен?

**Comment by glebqip** [comment]
Не знаю

**Comment by alexeib1** [comment]
кстати говоря, за сегодняшнее время ошибок в консоле не было, но на сервере оставались так называемые поезда "призраки" и именно Ема, заскринить не успел, если еще увижу заскриню, хочется узнать баг ли это? тоесть получается что физганом он не берется пройти сквозь него можно и спавнить вагоны он не мешает...

**Comment by glebqip** [comment]
Это какой-то движковый баг.
