### ISSUE TITLE
gm_mus_orange_metro_h

### ISSUE THREAD

**Issue by alexeib1** [glebqip/metrostroi_beta#74]
Не переключется стрелка в ПТО 2 канава, ни в диспетчерской, ни ДУРОЙ

**Comment by Hellss** [comment]
track switch переводит ее

**Comment by Hellss** [comment]
надо в диспетчерской перевести на 2 путь потом track switch поставить

**Comment by alexeib1** [comment]
так зачем такой огород городить? пофиксить никак?

**Comment by glebqip** [comment]
Это к автору карты
