### ISSUE TITLE
Error when spawning trains

### ISSUE THREAD

**Issue by TheTiceisRight** [glebqip/metrostroi_beta#76]
Not sure if it's my installation of Metrostroi Beta or if it's with the addon, but after updating from commit c0f9189 to commit b2c004a I've been unable to use the addon. Everything loads and seems fine, the issue is when I spawn a train. The train spawner doesn't work at all, and when I try to just spawn a wagon (from the entities -> Metrostroi [Trains]) the model spawns but nothing seems to appear (doors or anything in the front cab) When spawning it shows an error in the console, I've tried a few different trains and here are the resulting errors:
**81-717 MVM**: 
`[ERROR] addons/metrostroi/lua/entities/gmod_subway_base/cl_init.lua:282: attempt to index field 'train' (a nil value)
  1. SpawnCSEnt - addons/metrostroi/lua/entities/gmod_subway_base/cl_init.lua:282
   2. CreateCSEnts - addons/metrostroi/lua/entities/gmod_subway_base/cl_init.lua:325
    3. Think - addons/metrostroi/lua/entities/gmod_subway_base/cl_init.lua:529
     4. unknown - addons/metrostroi/lua/entities/gmod_subway_81-717_mvm/cl_init.lua:1791

[ERROR] addons/metrostroi/lua/entities/gmod_subway_base/cl_init.lua:282: attempt to index field 'train' (a nil value)
  1. SpawnCSEnt - addons/metrostroi/lua/entities/gmod_subway_base/cl_init.lua:282
   2. CreateCSEnts - addons/metrostroi/lua/entities/gmod_subway_base/cl_init.lua:325
    3. Think - addons/metrostroi/lua/entities/gmod_subway_base/cl_init.lua:555
     4. unknown - addons/metrostroi/lua/entities/gmod_subway_81-717_mvm/cl_init.lua:1791

[ERROR] addons/metrostroi/lua/entities/gmod_subway_81-717_mvm/cl_init.lua:1769: attempt to index field 'train' (a nil value)
  1. UpdateTextures - addons/metrostroi/lua/entities/gmod_subway_81-717_mvm/cl_init.lua:1769
   2. unknown - addons/metrostroi/lua/entities/gmod_subway_81-717_mvm/cl_init.lua:1794

[ERROR] addons/metrostroi/lua/entities/gmod_subway_81-717_mvm/cl_init.lua:1769: attempt to index field 'train' (a nil value)
  1. UpdateTextures - addons/metrostroi/lua/entities/gmod_subway_81-717_mvm/cl_init.lua:1769
   2. unknown - addons/metrostroi/lua/entities/gmod_subway_81-717_mvm/cl_init.lua:1798

[ERROR] addons/metrostroi/lua/entities/gmod_subway_81-717_mvm/cl_init.lua:1769: attempt to index field 'train' (a nil value)
  1. UpdateTextures - addons/metrostroi/lua/entities/gmod_subway_81-717_mvm/cl_init.lua:1769
   2. unknown - addons/metrostroi/lua/entities/gmod_subway_81-717_mvm/cl_init.lua:1802
`

**Ezh3**: 
`[ERROR] addons/metrostroi/lua/entities/gmod_subway_base/cl_init.lua:282: attempt to index field 'train' (a nil value)
  1. SpawnCSEnt - addons/metrostroi/lua/entities/gmod_subway_base/cl_init.lua:282
   2. CreateCSEnts - addons/metrostroi/lua/entities/gmod_subway_base/cl_init.lua:325
    3. Think - addons/metrostroi/lua/entities/gmod_subway_base/cl_init.lua:529
     4. unknown - addons/metrostroi/lua/entities/gmod_subway_ezh3/cl_init.lua:1009

[ERROR] addons/metrostroi/lua/entities/gmod_subway_base/cl_init.lua:282: attempt to index field 'train' (a nil value)
  1. SpawnCSEnt - addons/metrostroi/lua/entities/gmod_subway_base/cl_init.lua:282
   2. CreateCSEnts - addons/metrostroi/lua/entities/gmod_subway_base/cl_init.lua:325
    3. Think - addons/metrostroi/lua/entities/gmod_subway_base/cl_init.lua:555
     4. unknown - addons/metrostroi/lua/entities/gmod_subway_ezh3/cl_init.lua:1009

[ERROR] addons/metrostroi/lua/entities/gmod_subway_ezh3/cl_init.lua:987: attempt to index field 'train' (a nil value)
  1. UpdateTextures - addons/metrostroi/lua/entities/gmod_subway_ezh3/cl_init.lua:987
   2. unknown - addons/metrostroi/lua/entities/gmod_subway_ezh3/cl_init.lua:1012

[ERROR] addons/metrostroi/lua/entities/gmod_subway_ezh3/cl_init.lua:987: attempt to index field 'train' (a nil value)
  1. UpdateTextures - addons/metrostroi/lua/entities/gmod_subway_ezh3/cl_init.lua:987
   2. unknown - addons/metrostroi/lua/entities/gmod_subway_ezh3/cl_init.lua:1016

[ERROR] addons/metrostroi/lua/entities/gmod_subway_ezh3/cl_init.lua:987: attempt to index field 'train' (a nil value)
  1. UpdateTextures - addons/metrostroi/lua/entities/gmod_subway_ezh3/cl_init.lua:987
   2. unknown - addons/metrostroi/lua/entities/gmod_subway_ezh3/cl_init.lua:1020
`

**Comment by glebqip** [comment]
Ohh, another...
Step 1 - delete a LUA folder from metrostroi addon on server
Step 2 - copy LUA folder from github metrostroi to metrostroi addon on server

**Comment by TheTiceisRight** [comment]
Deleting and re copying the Lua folder fixed it. I'm guessing it was a file moved from one update to the other that screwed it up.
