### ISSUE TITLE
Консоль сервера (error's)

### ISSUE THREAD

**Issue by alexeib1** [glebqip/metrostroi_beta#77]
карта **gm_mus_orange_metro_h**
![default](https://cloud.githubusercontent.com/assets/17434146/13506858/31b5fc62-e1aa-11e5-872a-205227451543.png)
![2](https://cloud.githubusercontent.com/assets/17434146/13506857/31b3f58e-e1aa-11e5-90bf-0c39182fefc6.png)

а тут **опечатка**
![3](https://cloud.githubusercontent.com/assets/17434146/13506867/3d5dc658-e1aa-11e5-9853-c6dafc30811b.png)

**Comment by glebqip** [comment]
Насчет первого - а как ты вообще информатор заставил работать? На ЕмА его нет. Второе и третье профикшу

**Comment by alexeib1** [comment]
кто то из игроков, хз вообще как

**Comment by alexeib1** [comment]
![default](https://cloud.githubusercontent.com/assets/17434146/13527684/198ed65e-e23b-11e5-8400-7f3212a13dcb.png)
вот еще ошибка, уже сегодня

**Comment by alexeib1** [comment]
иногда когда некоторые игроки спавнять вагоны начинается вот такой вот флуд, продолжается до тех пор пока не удалишь состав. Вроде как только с ЛВЗ ( но это не точно )
![2](https://cloud.githubusercontent.com/assets/17434146/13531833/bed4783c-e252-11e5-8542-0bdaa5c4ccf1.png)

**Comment by glebqip** [comment]
Насчёт TrackPosition - Track Switch - стрелка. Для её работы нужно перезагрузить сигналку с сохранением. Если сигналку не делали - какой-то игрок её заспавнил

Насчёт station: - включи автомат Radio в LVZ рядом с A5, это дебаг, который я забыл выпилить
