### ISSUE TITLE
error in console sys_aspn

### ISSUE THREAD

**Issue by alexeib1** [glebqip/metrostroi_beta#83]
Ошибка, карта **gm_mus_orange_metro_h**
P.S Последние обновления с гитхаба стоят.
![default](https://cloud.githubusercontent.com/assets/17434146/13554934/8b6ea9c6-e3de-11e5-863a-85ef26fd1065.png)

**Comment by alexeib1** [comment]
баг
![2](https://cloud.githubusercontent.com/assets/17434146/13555594/9ae7808e-e3ee-11e5-918a-816ab7a9aab1.png)

**Comment by glebqip** [comment]
Первое посмотрю, второе не фиксится.
