### ISSUE TITLE
Ошибки сервера в коммите 142

### ISSUE THREAD

**Issue by flydvorkin** [glebqip/metrostroi_beta#87]
[ERROR] addons/metrostroi/lua/metrostroi/systems/sys_pa-m.lua:739: attempt to concatenate a nil value
  1. PAM - addons/metrostroi/lua/metrostroi/systems/sys_pa-m.lua:739
   2. func - addons/metrostroi/lua/entities/gmod_subway_81-717_lvz/cl_init.lua:2732
    3. DrawOnPanel - addons/metrostroi/lua/entities/gmod_subway_base/cl_init.lua:846
     4. DrawPost - addons/metrostroi/lua/entities/gmod_subway_81-717_lvz/cl_init.lua:2732
      5. fn - addons/metrostroi/lua/entities/gmod_subway_base/cl_init.lua:382
       6. unknown - addons/ulib/lua/ulib/shared/hook.lua:110

[ERROR] addons/metrostroi/lua/metrostroi/systems/sys_pa-ksd-m.lua:1294: attempt to index field 'FirstStation' (a number value)
  1. Trigger - addons/metrostroi/lua/metrostroi/systems/sys_pa-ksd-m.lua:1294
   2. Think - addons/metrostroi/lua/metrostroi/systems/sys_pa-ksd-m.lua:1940
    3. Think - addons/metrostroi/lua/entities/gmod_subway_base/init.lua:1646
     4. unknown - addons/metrostroi/lua/entities/gmod_subway_81-717_lvz/init.lua:456

[ERROR] addons/metrostroi/lua/metrostroi/systems/sys_pa-ksd-m.lua:1329: attempt to get length of field 'FirstStation' (a number value)
  1. Trigger - addons/metrostroi/lua/metrostroi/systems/sys_pa-ksd-m.lua:1329
   2. Think - addons/metrostroi/lua/metrostroi/systems/sys_pa-ksd-m.lua:1940
    3. Think - addons/metrostroi/lua/entities/gmod_subway_base/init.lua:1646
     4. unknown - addons/metrostroi/lua/entities/gmod_subway_81-717_lvz/init.lua:456

[ERROR] addons/ulib/lua/ulib/shared/sh_ucl.lua:42: attempt to index local 'ply' (a nil value)
  1. query - addons/ulib/lua/ulib/shared/sh_ucl.lua:42
   2. Think - addons/metrostroi/lua/metrostroi/systems/sys_bars.lua:737
    3. Think - addons/metrostroi/lua/entities/gmod_subway_base/init.lua:1646
     4. unknown - addons/metrostroi/lua/entities/gmod_subway_81-717_lvz/init.lua:456

**Comment by glebqip** [comment]
Последняя ошибка к метрострою не относится, я не нашёл ничего что могло бы её у нас вызывать, остальные исправятся с след апдейтом

**Comment by flydvorkin** [comment]
да, последняя была просто глюком. она не воспроизводится.
на паксд-м еще кнопкой отмена не получается стереть цифры набраной станции чтоб переправить конечную например.

**Comment by glebqip** [comment]
2c41cd9f25d3da3547cc7691ac8074d029fd18a3

**Comment by flydvorkin** [comment]
Огромное спасибо за обновление! :-) все работает отлично!
