### ISSUE TITLE
Linux

### ISSUE THREAD

**Issue by alexeib1** [glebqip/metrostroi_beta#89]
Интересует такой вопрос, возможно ли как то захостить сервер Метростроя на Linux? и есть ли турбострой под linux?

**Comment by glebqip** [comment]
Турбостроя нормального под linux нет. Запустить можно как и любой другой мод

**Comment by alexeib1** [comment]
да запустить то понятно что можно, я имею ввиду также без лагов как с турбостроем, просто не все хостинги дают сервера под win

**Comment by glebqip** [comment]
Нет, без лагов не получится наверное. Проверь турбострой линуксовый в Steam обсуждениях, там какой то есть

**Comment by cyber-dream** [comment]
This issue was moved to metrostroi-beta/metrostroi_beta#7
